### ISSUE TITLE
had to alter build by one line

### ISSUE THREAD

**Issue by marchage** [vors/choco-rustup#1]
Hello,

Since it's in beta over at chocolatey I decided to check the soure, which resulted in cloning building etc. But on windows 10 I got a download error running `/.build.ps1` as instructed:

```
Exception calling "DownloadFile" with "2" argument(s): "The request was aborted: Could not create SSL/TLS
secure channel."
At C:\Users\marchage\source\repos\choco-rustup\build.ps1:19 char:1
+ (New-Object System.Net.WebClient).DownloadFile($url, $package)
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : WebException
```

It went away when I specified tls 1.2 to be used by adding the following line above the actual webclient downloadfile call:
```
[System.Net.ServicePointManager]::SecurityProtocol = [System.Net.SecurityProtocolType]::Tls12;
```

I also specified url to be https, since rustup website redirects there anyway. Hope this helps,

Marc

**Comment by vors** [comment]
Yes, good point - I think that's more like a PowerShell problem and if you use pwsh 6+ that should not be the problem anymore because it got fixed. Thank you for the note!
